 

class InstructionDefinition:
    def __init__(self, name, operands_number, cycles):
        self.name = name
        self.operands_number = operands_number
        self.cycles = cycles

class Instruction:
    def __init__(self, definition:InstructionDefinition, operands):
        self.definition = definition
        self.operands = operands

INSTRUCTION_DICT = {
    0x00: InstructionDefinition('NOP', 0, 1),

    0x80: InstructionDefinition('ADD_B', 0, 1),
    0x81: InstructionDefinition('ADD_C', 0, 1),
    0x82: InstructionDefinition('ADD_D', 0, 1),
    0x83: InstructionDefinition('ADD_E', 0, 1),
    0x84: InstructionDefinition('ADD_H', 0, 1),
    0x85: InstructionDefinition('ADD_L', 0, 1),
    0x86: InstructionDefinition('ADD_HL', 0, 2),
    0x87: InstructionDefinition('ADD_A', 0, 1),
    0xc6: InstructionDefinition('ADD_D8', 1, 2),

    0x88: InstructionDefinition('ADDC_B', 0, 1),
    0x89: InstructionDefinition('ADDC_C', 0, 1),
    0x8a: InstructionDefinition('ADDC_D', 0, 1),
    0x8b: InstructionDefinition('ADDC_E', 0, 1),
    0x8c: InstructionDefinition('ADDC_H', 0, 1),
    0x8d: InstructionDefinition('ADDC_L', 0, 1),
    0x8e: InstructionDefinition('ADDC_HL', 0, 2),
    0x8f: InstructionDefinition('ADDC_A', 0, 1),
    0xce: InstructionDefinition('ADDC_D8', 1, 2),

    0xe9: InstructionDefinition('JP_HL', 0, 1),
    0xc3: InstructionDefinition('JP_D16', 2, 4),
    0xc2: InstructionDefinition('JP_NZ', 2, 3),
    0xd2: InstructionDefinition('JP_NC', 2, 3),
    0xca: InstructionDefinition('JP_Z', 2, 3),
    0xda: InstructionDefinition('JP_C', 2, 3),

    0x18: InstructionDefinition('JPR_D16', 1, 2),
    0x20: InstructionDefinition('JPR_NZ', 1, 2),
    0x30: InstructionDefinition('JPR_NC', 1, 2),
    0x28: InstructionDefinition('JPR_Z', 1, 2),
    0x38: InstructionDefinition('JPR_C', 1, 2),

    0xa0: InstructionDefinition('AND_B', 0, 1),
    0xa1: InstructionDefinition('AND_C', 0, 1),
    0xa2: InstructionDefinition('AND_D', 0, 1),
    0xa3: InstructionDefinition('AND_E', 0, 1),
    0xa4: InstructionDefinition('AND_H', 0, 1),
    0xa5: InstructionDefinition('AND_L', 0, 1),
    0xa6: InstructionDefinition('AND_HL', 0, 1),
    0xa7: InstructionDefinition('AND_A', 0, 1),
    0xe6: InstructionDefinition('AND_D8', 1, 2),

    0xcd: InstructionDefinition('CALL_D16', 2, 6),
    0xc4: InstructionDefinition('CALL_NZ', 2, 3),
    0xd4: InstructionDefinition('CALL_NC', 2, 3),
    0xcc: InstructionDefinition('CALL_Z', 2, 3),
    0xdc: InstructionDefinition('CALL_C', 2, 3),

    0xc9: InstructionDefinition('RET_D16', 0, 4),
    0xc0: InstructionDefinition('RET_NZ', 0, 2),
    0xd0: InstructionDefinition('RET_NC', 0, 2),
    0xc8: InstructionDefinition('RET_Z', 0, 2),
    0xd8: InstructionDefinition('RET_C', 0, 2),

    0x09: InstructionDefinition('ADDHL_BC', 0, 2),
    0x19: InstructionDefinition('ADDHL_DE', 0, 2),
    0x29: InstructionDefinition('ADDHL_HL', 0, 2),
    0x39: InstructionDefinition('ADDHL_SP', 0, 2),

    0xe8: InstructionDefinition('ADDSP_D8', 1, 2),

    0x3f: InstructionDefinition('CCF', 0, 1),
    0x2f: InstructionDefinition('CPL', 0, 1),
    0x27: InstructionDefinition('DAA', 0, 1),

    0xb8: InstructionDefinition('CP_B', 0, 1),
    0xb9: InstructionDefinition('CP_C', 0, 1),
    0xba: InstructionDefinition('CP_D', 0, 1),
    0xbb: InstructionDefinition('CP_E', 0, 1),
    0xbc: InstructionDefinition('CP_H', 0, 1),
    0xbd: InstructionDefinition('CP_L', 0, 1),
    0xbe: InstructionDefinition('CP_HL', 0, 2),
    0xbf: InstructionDefinition('CP_A', 0, 1),
    0xfe: InstructionDefinition('CP_D8', 1, 2),

    0x05: InstructionDefinition('DEC_B', 0, 1),
    0x0d: InstructionDefinition('DEC_C', 0, 1),
    0x15: InstructionDefinition('DEC_D', 0, 1),
    0x1d: InstructionDefinition('DEC_E', 0, 1),
    0x25: InstructionDefinition('DEC_H', 0, 1),
    0x2d: InstructionDefinition('DEC_L', 0, 1),
    0x3d: InstructionDefinition('DEC_A', 0, 1),
    0x35: InstructionDefinition('DEC_HL', 0, 3),

    0x2b: InstructionDefinition('DEC16_HL', 0, 2),
    0x0b: InstructionDefinition('DEC16_BC', 0, 2),
    0x1b: InstructionDefinition('DEC16_DE', 0, 2),
    0x3b: InstructionDefinition('DEC16_SP', 0, 2),

    0x04: InstructionDefinition('INC_B', 0, 1),
    0x0c: InstructionDefinition('INC_C', 0, 1),
    0x14: InstructionDefinition('INC_D', 0, 1),
    0x1c: InstructionDefinition('INC_E', 0, 1),
    0x24: InstructionDefinition('INC_H', 0, 1),
    0x2c: InstructionDefinition('INC_L', 0 ,1),
    0x3c: InstructionDefinition('INC_A', 0, 1),
    0x34: InstructionDefinition('INC_HL', 0, 2),

    0x03: InstructionDefinition('INC16_BC', 0, 2),
    0x13: InstructionDefinition('INC16_DE', 0, 2),
    0x23: InstructionDefinition('INC16_HL', 0, 2),
    0x33: InstructionDefinition('INC16_SP', 0, 2),

    0xf3: InstructionDefinition('DI', 0, 1),
    0xfb: InstructionDefinition('EI', 0, 1),
    0x76: InstructionDefinition('HALT', 0, 1),
    0xd9: InstructionDefinition('RETI', 0, 4),
    0x10: InstructionDefinition('STOP', 1, 0),

    0x37: InstructionDefinition('SCF', 0, 1),


    ## Infinite load instructions
    0x40: InstructionDefinition('LD_B_B', 0, 1),
    0x41: InstructionDefinition('LD_B_C', 0, 1),
    0x42: InstructionDefinition('LD_B_D', 0, 1),
    0x43: InstructionDefinition('LD_B_E', 0, 1),
    0x44: InstructionDefinition('LD_B_H', 0, 1),
    0x45: InstructionDefinition('LD_B_L', 0, 1),
    0x47: InstructionDefinition('LD_B_A', 0, 1),

    0x48: InstructionDefinition('LD_C_B', 0, 1),
    0x49: InstructionDefinition('LD_C_C', 0, 1),
    0x4a: InstructionDefinition('LD_C_D', 0, 1),
    0x4b: InstructionDefinition('LD_C_E', 0, 1),
    0x4c: InstructionDefinition('LD_C_H', 0, 1),
    0x4d: InstructionDefinition('LD_C_L', 0, 1),
    0x4f: InstructionDefinition('LD_C_A', 0, 1),

    0x50: InstructionDefinition('LD_D_B', 0, 1),
    0x51: InstructionDefinition('LD_D_C', 0, 1),
    0x52: InstructionDefinition('LD_D_D', 0, 1),
    0x53: InstructionDefinition('LD_D_E', 0, 1),
    0x54: InstructionDefinition('LD_D_H', 0, 1),
    0x55: InstructionDefinition('LD_D_L', 0, 1),
    0x57: InstructionDefinition('LD_D_A', 0, 1),

    0x58: InstructionDefinition('LD_E_B', 0, 1),
    0x59: InstructionDefinition('LD_E_C', 0, 1),
    0x5a: InstructionDefinition('LD_E_D', 0, 1),
    0x5b: InstructionDefinition('LD_E_E', 0, 1),
    0x5c: InstructionDefinition('LD_E_H', 0, 1),
    0x5d: InstructionDefinition('LD_E_L', 0, 1),
    0x5f: InstructionDefinition('LD_E_A', 0, 1),

    0x60: InstructionDefinition('LD_H_B', 0, 1),
    0x61: InstructionDefinition('LD_H_C', 0, 1),
    0x62: InstructionDefinition('LD_H_D', 0, 1),
    0x63: InstructionDefinition('LD_H_E', 0, 1),
    0x64: InstructionDefinition('LD_H_H', 0, 1),
    0x65: InstructionDefinition('LD_H_L', 0, 1),
    0x67: InstructionDefinition('LD_H_A', 0, 1),

    0x68: InstructionDefinition('LD_L_B', 0, 1),
    0x69: InstructionDefinition('LD_L_C', 0, 1),
    0x6a: InstructionDefinition('LD_L_D', 0, 1),
    0x6b: InstructionDefinition('LD_L_E', 0, 1),
    0x6c: InstructionDefinition('LD_L_H', 0, 1),
    0x6d: InstructionDefinition('LD_L_L', 0, 1),
    0x6f: InstructionDefinition('LD_L_A', 0, 1),

    0x78: InstructionDefinition('LD_A_B', 0, 1),
    0x79: InstructionDefinition('LD_A_C', 0, 1),
    0x7a: InstructionDefinition('LD_A_D', 0, 1),
    0x7b: InstructionDefinition('LD_A_E', 0, 1),
    0x7c: InstructionDefinition('LD_A_H', 0, 1),
    0x7d: InstructionDefinition('LD_A_L', 0, 1),
    0x7f: InstructionDefinition('LD_A_A', 0, 1),

    0x70: InstructionDefinition('LD_HL_B', 0, 2),
    0x71: InstructionDefinition('LD_HL_C', 0, 2),
    0x72: InstructionDefinition('LD_HL_D', 0, 2),
    0x73: InstructionDefinition('LD_HL_E', 0, 2),
    0x74: InstructionDefinition('LD_HL_H', 0, 2),
    0x75: InstructionDefinition('LD_HL_L', 0, 2),
    0x77: InstructionDefinition('LD_HL_A', 0, 2),

    0x46: InstructionDefinition('LD_B_HL', 0, 2),
    0x4e: InstructionDefinition('LD_C_HL', 0, 2),
    0x56: InstructionDefinition('LD_D_HL', 0, 2),
    0x5e: InstructionDefinition('LD_E_HL', 0, 2),
    0x66: InstructionDefinition('LD_H_HL', 0, 2),
    0x6e: InstructionDefinition('LD_L_HL', 0, 2),
    0x7e: InstructionDefinition('LD_A_HL', 0, 2),

    0x06: InstructionDefinition('LD_B_D8', 1, 2),
    0x0e: InstructionDefinition('LD_C_D8', 1, 2),
    0x16: InstructionDefinition('LD_D_D8', 1, 2),
    0x1e: InstructionDefinition('LD_E_D8', 1, 2),
    0x26: InstructionDefinition('LD_H_D8', 1, 2),
    0x2e: InstructionDefinition('LD_L_D8', 1, 2),
    0x3e: InstructionDefinition('LD_A_D8', 1, 2),
    0x36: InstructionDefinition('LD_HL_D8', 1, 3),

    0x02: InstructionDefinition('LDP_BC_A', 0, 2),
    0x12: InstructionDefinition('LDP_DE_A', 0, 2),
    0x0a: InstructionDefinition('LDP_A_BC', 0, 2),
    0x1a: InstructionDefinition('LDP_A_DE', 0, 2),
    0xfa: InstructionDefinition('LDP_A_D16', 2, 4),
    0xea: InstructionDefinition('LDP_D16_A', 2, 4),
    0x22: InstructionDefinition('LDP_HLI_A', 0, 2),
    0x32: InstructionDefinition('LDP_HLD_A', 0, 2),
    0x2a: InstructionDefinition('LDP_A_HLI', 0, 2),
    0x3a: InstructionDefinition('LDP_A_HLD', 0, 2),

    0x01: InstructionDefinition('LD16_BC_D16', 2, 3),
    0x11: InstructionDefinition('LD16_DE_D16', 2, 3),
    0x21: InstructionDefinition('LD16_HL_D16', 2, 3),
    0x31: InstructionDefinition('LD16_SP_D16', 2, 3),
    
    0x08: InstructionDefinition('LDS_D16_SP', 2, 5),
    0xf9: InstructionDefinition('LDS_SP_HL', 0, 1),
    0xf8: InstructionDefinition('LDS_HL_SPe', 1, 3),

    0xf0: InstructionDefinition('LDH_A_D8', 1, 3),
    0xf2: InstructionDefinition('LDH_A_C', 0, 2),
    0xe2: InstructionDefinition('LDH_C_A', 0, 2),
    0xe0: InstructionDefinition('LDH_D8_A', 1, 3),


    0xb0: InstructionDefinition('OR_B', 0, 1),
    0xb1: InstructionDefinition('OR_C', 0, 1),
    0xb2: InstructionDefinition('OR_D', 0, 1),
    0xb3: InstructionDefinition('OR_E', 0, 1),
    0xb4: InstructionDefinition('OR_H', 0, 1),
    0xb5: InstructionDefinition('OR_L', 0, 1),
    0xb7: InstructionDefinition('OR_A', 0, 1),
    0xb6: InstructionDefinition('OR_HL', 0, 1),
    0xf6: InstructionDefinition('OR_D8', 1, 1),

    0xf1: InstructionDefinition('POP_AF', 0, 3),
    0xc1: InstructionDefinition('POP_BC', 0, 3),
    0xd1: InstructionDefinition('POP_DE', 0, 3),
    0xe1: InstructionDefinition('POP_HL', 0, 3),

    0xf5: InstructionDefinition('PUSH_AF', 0, 4),
    0xc5: InstructionDefinition('PUSH_BC', 0, 4),
    0xd5: InstructionDefinition('PUSH_DE', 0, 4),
    0xe5: InstructionDefinition('PUSH_HL', 0, 4),

    0x90: InstructionDefinition('SUB_B', 0 , 1),
    0x91: InstructionDefinition('SUB_C', 0 , 1),
    0x92: InstructionDefinition('SUB_D', 0 , 1),
    0x93: InstructionDefinition('SUB_E', 0 , 1),
    0x94: InstructionDefinition('SUB_H', 0 , 1),
    0x95: InstructionDefinition('SUB_L', 0 , 1),
    0x96: InstructionDefinition('SUB_HL', 0 , 2),
    0x97: InstructionDefinition('SUB_A', 0 , 1),
    0xd6: InstructionDefinition('SUB_D8', 1 , 2),

    0x98: InstructionDefinition('SUBC_B', 0 , 1),
    0x99: InstructionDefinition('SUBC_C', 0 , 1),
    0x9a: InstructionDefinition('SUBC_D', 0 , 1),
    0x9b: InstructionDefinition('SUBC_E', 0 , 1),
    0x9c: InstructionDefinition('SUBC_H', 0 , 1),
    0x9d: InstructionDefinition('SUBC_L', 0 , 1),
    0x9e: InstructionDefinition('SUBC_HL', 0 , 2),
    0x9f: InstructionDefinition('SUBC_A', 0 , 1),
    0xde: InstructionDefinition('SUBC_D8', 1 , 2),

    0xa8: InstructionDefinition('XOR_B', 0, 1),
    0xa9: InstructionDefinition('XOR_C', 0, 1),
    0xaa: InstructionDefinition('XOR_D', 0, 1),
    0xab: InstructionDefinition('XOR_E', 0, 1),
    0xac: InstructionDefinition('XOR_H', 0, 1),
    0xad: InstructionDefinition('XOR_L', 0, 1),
    0xae: InstructionDefinition('XOR_HL', 0, 2),
    0xaf: InstructionDefinition('XOR_A', 0, 1),
    0xee: InstructionDefinition('XOR_D8', 1, 2),

    0x07: InstructionDefinition('RLCA_A', 0, 1),
    0x0f: InstructionDefinition('RRCA_A', 0 ,1),
    0x17: InstructionDefinition('RLA_A', 0, 1),
    0x1f: InstructionDefinition('RRA_A', 0, 1),

    0xc7: InstructionDefinition('RST_0', 0, 4),
    0xd7: InstructionDefinition('RST_1', 0, 4),
    0xe7: InstructionDefinition('RST_2', 0, 4),
    0xf7: InstructionDefinition('RST_3', 0, 4),
    0xcf: InstructionDefinition('RST_4', 0, 4),
    0xdf: InstructionDefinition('RST_5', 0, 4),
    0xef: InstructionDefinition('RST_6', 0, 4),
    0xff: InstructionDefinition('RST_7', 0, 4),

}

PREFIX_INSTRUCTION_DICT = {

    0x10: InstructionDefinition('RL_B', 0, 2),
    0x11: InstructionDefinition('RL_C', 0, 2),
    0x12: InstructionDefinition('RL_D', 0, 2),
    0x13: InstructionDefinition('RL_E', 0, 2),
    0x14: InstructionDefinition('RL_H', 0 ,2),
    0x15: InstructionDefinition('RL_L', 0 ,2),
    0x16: InstructionDefinition('RL_HL', 0, 4),
    0x17: InstructionDefinition('RL_A', 0, 1),

    0x00: InstructionDefinition('RLC_B', 0 , 2),
    0x01: InstructionDefinition('RLC_C', 0 , 2),
    0x02: InstructionDefinition('RLC_D', 0 , 2),
    0x03: InstructionDefinition('RLC_E', 0 , 2),
    0x04: InstructionDefinition('RLC_H', 0 , 2),
    0x05: InstructionDefinition('RLC_L', 0 , 2),
    0x06: InstructionDefinition('RLC_HL', 0 , 4),
    0x07: InstructionDefinition('RLC_A', 0 , 1),

    0x18: InstructionDefinition('RR_B', 0, 2),
    0x19: InstructionDefinition('RR_C', 0, 2),
    0x1a: InstructionDefinition('RR_D', 0, 2),
    0x1b: InstructionDefinition('RR_E', 0, 2),
    0x1c: InstructionDefinition('RR_H', 0, 2),
    0x1d: InstructionDefinition('RR_L', 0, 2),
    0x1e: InstructionDefinition('RR_HL', 0, 4),
    0x1f: InstructionDefinition('RR_A', 0, 1),

    0x08: InstructionDefinition('RRC_B', 0, 2),
    0x09: InstructionDefinition('RRC_C', 0, 2),
    0x0a: InstructionDefinition('RRC_D', 0, 2),
    0x0b: InstructionDefinition('RRC_E', 0, 2),
    0x0c: InstructionDefinition('RRC_H', 0, 2),
    0x0d: InstructionDefinition('RRC_L', 0, 2),
    0x0e: InstructionDefinition('RRC_HL', 0, 4),
    0x0f: InstructionDefinition('RRC_A', 0, 1),
    
    0x40: InstructionDefinition('BIT_B_0', 0, 2),
    0x41: InstructionDefinition('BIT_C_0', 0, 2), 
    0x42: InstructionDefinition('BIT_D_0', 0, 2),
    0x43: InstructionDefinition('BIT_E_0', 0, 2),
    0x44: InstructionDefinition('BIT_H_0', 0, 2),
    0x45: InstructionDefinition('BIT_L_0', 0, 2),
    0x46: InstructionDefinition('BIT_HL_0', 0, 2),
    0x47: InstructionDefinition('BIT_A_0', 0, 2),

    0x48: InstructionDefinition('BIT_B_1', 0, 2),
    0x49: InstructionDefinition('BIT_C_1', 0, 2),
    0x4a: InstructionDefinition('BIT_D_1', 0, 2),
    0x4b: InstructionDefinition('BIT_E_1', 0, 2),
    0x4c: InstructionDefinition('BIT_H_1', 0, 2),
    0x4d: InstructionDefinition('BIT_L_1', 0, 2),
    0x4e: InstructionDefinition('BIT_HL_1', 0, 3),
    0x4f: InstructionDefinition('BIT_A_1', 0, 2),

    0x50: InstructionDefinition('BIT_B_2', 0, 2),
    0x51: InstructionDefinition('BIT_C_2', 0, 2),
    0x52: InstructionDefinition('BIT_D_2', 0, 2),
    0x53: InstructionDefinition('BIT_E_2', 0, 2),
    0x54: InstructionDefinition('BIT_H_2', 0, 2),
    0x55: InstructionDefinition('BIT_L_2', 0, 2),
    0x56: InstructionDefinition('BIT_HL_2', 0, 3),
    0x57: InstructionDefinition('BIT_A_2', 0, 2),

    0x58: InstructionDefinition('BIT_B_3', 0, 2),
    0x59: InstructionDefinition('BIT_C_3', 0, 2),
    0x5a: InstructionDefinition('BIT_D_3', 0, 2),
    0x5b: InstructionDefinition('BIT_E_3', 0, 2),
    0x5c: InstructionDefinition('BIT_H_3', 0, 2),
    0x5d: InstructionDefinition('BIT_L_3', 0, 2),
    0x5e: InstructionDefinition('BIT_HL_3', 0, 3),
    0x5f: InstructionDefinition('BIT_A_3', 0, 2),

    0x60: InstructionDefinition('BIT_B_4', 0, 2),
    0x61: InstructionDefinition('BIT_C_4', 0, 2),
    0x62: InstructionDefinition('BIT_D_4', 0, 2),
    0x63: InstructionDefinition('BIT_E_4', 0, 2),
    0x64: InstructionDefinition('BIT_H_4', 0, 2),
    0x65: InstructionDefinition('BIT_L_4', 0, 2),
    0x66: InstructionDefinition('BIT_HL_4', 0, 3),
    0x67: InstructionDefinition('BIT_A_4', 0, 2),

    0x68: InstructionDefinition('BIT_B_5', 0, 2),
    0x69: InstructionDefinition('BIT_C_5', 0, 2),
    0x6a: InstructionDefinition('BIT_D_5', 0, 2),
    0x6b: InstructionDefinition('BIT_E_5', 0, 2),
    0x6c: InstructionDefinition('BIT_H_5', 0, 2),
    0x6d: InstructionDefinition('BIT_L_5', 0, 2),
    0x6e: InstructionDefinition('BIT_HL_5', 0, 3),
    0x6f: InstructionDefinition('BIT_A_5', 0, 2),

    0x70: InstructionDefinition('BIT_B_6', 0, 2),
    0x71: InstructionDefinition('BIT_C_6', 0, 2),
    0x72: InstructionDefinition('BIT_D_6', 0, 2),
    0x73: InstructionDefinition('BIT_E_6', 0, 2),
    0x74: InstructionDefinition('BIT_H_6', 0, 2),
    0x75: InstructionDefinition('BIT_L_6', 0, 2),
    0x76: InstructionDefinition('BIT_HL_6', 0, 3),
    0x77: InstructionDefinition('BIT_A_6', 0, 2),

    0x78: InstructionDefinition('BIT_B_7', 0, 2),
    0x79: InstructionDefinition('BIT_C_7', 0, 2),
    0x7a: InstructionDefinition('BIT_D_7', 0, 2),
    0x7b: InstructionDefinition('BIT_E_7', 0, 2),
    0x7c: InstructionDefinition('BIT_H_7', 0, 2),
    0x7d: InstructionDefinition('BIT_L_7', 0, 2),
    0x7e: InstructionDefinition('BIT_HL_7', 0, 3),
    0x7f: InstructionDefinition('BIT_A_7', 0, 2),

    0x38: InstructionDefinition('SRL_B', 0 , 2),
    0x39: InstructionDefinition('SRL_C', 0 , 2),
    0x3a: InstructionDefinition('SRL_D', 0 , 2),
    0x3b: InstructionDefinition('SRL_E', 0 , 2),
    0x3c: InstructionDefinition('SRL_H', 0 , 2),
    0x3d: InstructionDefinition('SRL_L', 0 , 2),
    0x3e: InstructionDefinition('SRL_HL', 0 , 4),
    0x3f: InstructionDefinition('SRL_A', 0 , 2),

    0x30: InstructionDefinition('SWAP_B', 0, 2),
    0x31: InstructionDefinition('SWAP_C', 0, 2),
    0x32: InstructionDefinition('SWAP_D', 0, 2),
    0x33: InstructionDefinition('SWAP_E', 0, 2),
    0x34: InstructionDefinition('SWAP_H', 0, 2),
    0x35: InstructionDefinition('SWAP_L', 0, 2),
    0x36: InstructionDefinition('SWAP_HL', 0, 2),
    0x37: InstructionDefinition('SWAP_A', 0, 2),


    0x80: InstructionDefinition('RES_B_0', 0, 2),
    0x81: InstructionDefinition('RES_C_0', 0, 2),
    0x82: InstructionDefinition('RES_D_0', 0, 2),
    0x83: InstructionDefinition('RES_E_0', 0, 2),
    0x84: InstructionDefinition('RES_H_0', 0, 2),
    0x85: InstructionDefinition('RES_L_0', 0, 2),
    0x86: InstructionDefinition('RES_HL_0', 0, 4),
    0x87: InstructionDefinition('RES_A_0', 0, 2),
    
    0x88: InstructionDefinition('RES_B_1', 0, 2),
    0x89: InstructionDefinition('RES_C_1', 0, 2),
    0x8a: InstructionDefinition('RES_D_1', 0, 2),
    0x8b: InstructionDefinition('RES_E_1', 0, 2),
    0x8c: InstructionDefinition('RES_H_1', 0, 2),
    0x8d: InstructionDefinition('RES_L_1', 0, 2),
    0x8e: InstructionDefinition('RES_HL_1', 0, 4),
    0x8f: InstructionDefinition('RES_A_1', 0, 2),

    0x90: InstructionDefinition('RES_B_2', 0, 2),
    0x91: InstructionDefinition('RES_C_2', 0, 2),
    0x92: InstructionDefinition('RES_D_2', 0, 2),
    0x93: InstructionDefinition('RES_E_2', 0, 2),
    0x94: InstructionDefinition('RES_H_2', 0, 2),
    0x95: InstructionDefinition('RES_L_2', 0, 2),
    0x96: InstructionDefinition('RES_HL_2', 0, 4),
    0x97: InstructionDefinition('RES_A_2', 0, 2),
    
    0x98: InstructionDefinition('RES_B_3', 0, 2),
    0x99: InstructionDefinition('RES_C_3', 0, 2),
    0x9a: InstructionDefinition('RES_D_3', 0, 2),
    0x9b: InstructionDefinition('RES_E_3', 0, 2),
    0x9c: InstructionDefinition('RES_H_3', 0, 2),
    0x9d: InstructionDefinition('RES_L_3', 0, 2),
    0x9e: InstructionDefinition('RES_HL_3', 0, 4),
    0x9f: InstructionDefinition('RES_A_3', 0, 2),

    0xa0: InstructionDefinition('RES_B_4', 0, 2),
    0xa1: InstructionDefinition('RES_C_4', 0, 2),
    0xa2: InstructionDefinition('RES_D_4', 0, 2),
    0xa3: InstructionDefinition('RES_E_4', 0, 2),
    0xa4: InstructionDefinition('RES_H_4', 0, 2),
    0xa5: InstructionDefinition('RES_L_4', 0, 2),
    0xa6: InstructionDefinition('RES_HL_4', 0, 4),
    0xa7: InstructionDefinition('RES_A_4', 0, 2),
    
    0xa8: InstructionDefinition('RES_B_5', 0, 2),
    0xa9: InstructionDefinition('RES_C_5', 0, 2),
    0xaa: InstructionDefinition('RES_D_5', 0, 2),
    0xab: InstructionDefinition('RES_E_5', 0, 2),
    0xac: InstructionDefinition('RES_H_5', 0, 2),
    0xad: InstructionDefinition('RES_L_5', 0, 2),
    0xae: InstructionDefinition('RES_HL_5', 0, 4),
    0xaf: InstructionDefinition('RES_A_5', 0, 2),

    0xb0: InstructionDefinition('RES_B_6', 0, 2),
    0xb1: InstructionDefinition('RES_C_6', 0, 2),
    0xb2: InstructionDefinition('RES_D_6', 0, 2),
    0xb3: InstructionDefinition('RES_E_6', 0, 2),
    0xb4: InstructionDefinition('RES_H_6', 0, 2),
    0xb5: InstructionDefinition('RES_L_6', 0, 2),
    0xb6: InstructionDefinition('RES_HL_6', 0, 4),
    0xb7: InstructionDefinition('RES_A_6', 0, 2),
    
    0xb8: InstructionDefinition('RES_B_7', 0, 2),
    0xb9: InstructionDefinition('RES_C_7', 0, 2),
    0xba: InstructionDefinition('RES_D_7', 0, 2),
    0xbb: InstructionDefinition('RES_E_7', 0, 2),
    0xbc: InstructionDefinition('RES_H_7', 0, 2),
    0xbd: InstructionDefinition('RES_L_7', 0, 2),
    0xbe: InstructionDefinition('RES_HL_7', 0, 4),
    0xbf: InstructionDefinition('RES_A_7', 0, 2),


    0xc0: InstructionDefinition('SET_B_0', 0, 2),
    0xc1: InstructionDefinition('SET_C_0', 0, 2),
    0xc2: InstructionDefinition('SET_D_0', 0, 2),
    0xc3: InstructionDefinition('SET_E_0', 0, 2),
    0xc4: InstructionDefinition('SET_H_0', 0, 2),
    0xc5: InstructionDefinition('SET_L_0', 0, 2),
    0xc6: InstructionDefinition('SET_HL_0', 0, 4),
    0xc7: InstructionDefinition('SET_A_0', 0, 2),
    
    0xc8: InstructionDefinition('SET_B_1', 0, 2),
    0xc9: InstructionDefinition('SET_C_1', 0, 2),
    0xca: InstructionDefinition('SET_D_1', 0, 2),
    0xcb: InstructionDefinition('SET_E_1', 0, 2),
    0xcc: InstructionDefinition('SET_H_1', 0, 2),
    0xcd: InstructionDefinition('SET_L_1', 0, 2),
    0xce: InstructionDefinition('SET_HL_1', 0, 4),
    0xcf: InstructionDefinition('SET_A_1', 0, 2),

    0xd0: InstructionDefinition('SET_B_2', 0, 2),
    0xd1: InstructionDefinition('SET_C_2', 0, 2),
    0xd2: InstructionDefinition('SET_D_2', 0, 2),
    0xd3: InstructionDefinition('SET_E_2', 0, 2),
    0xd4: InstructionDefinition('SET_H_2', 0, 2),
    0xd5: InstructionDefinition('SET_L_2', 0, 2),
    0xd6: InstructionDefinition('SET_HL_2', 0, 4),
    0xd7: InstructionDefinition('SET_A_2', 0, 2),
    
    0xd8: InstructionDefinition('SET_B_3', 0, 2),
    0xd9: InstructionDefinition('SET_C_3', 0, 2),
    0xda: InstructionDefinition('SET_D_3', 0, 2),
    0xdb: InstructionDefinition('SET_E_3', 0, 2),
    0xdc: InstructionDefinition('SET_H_3', 0, 2),
    0xdd: InstructionDefinition('SET_L_3', 0, 2),
    0xde: InstructionDefinition('SET_HL_3', 0, 4),
    0xdf: InstructionDefinition('SET_A_3', 0, 2),

    0xe0: InstructionDefinition('SET_B_4', 0, 2),
    0xe1: InstructionDefinition('SET_C_4', 0, 2),
    0xe2: InstructionDefinition('SET_D_4', 0, 2),
    0xe3: InstructionDefinition('SET_E_4', 0, 2),
    0xe4: InstructionDefinition('SET_H_4', 0, 2),
    0xe5: InstructionDefinition('SET_L_4', 0, 2),
    0xe6: InstructionDefinition('SET_HL_4', 0, 4),
    0xe7: InstructionDefinition('SET_A_4', 0, 2),
    
    0xe8: InstructionDefinition('SET_B_5', 0, 2),
    0xe9: InstructionDefinition('SET_C_5', 0, 2),
    0xea: InstructionDefinition('SET_D_5', 0, 2),
    0xeb: InstructionDefinition('SET_E_5', 0, 2),
    0xec: InstructionDefinition('SET_H_5', 0, 2),
    0xed: InstructionDefinition('SET_L_5', 0, 2),
    0xee: InstructionDefinition('SET_HL_5', 0, 4),
    0xef: InstructionDefinition('SET_A_5', 0, 2),

    0xf0: InstructionDefinition('SET_B_6', 0, 2),
    0xf1: InstructionDefinition('SET_C_6', 0, 2),
    0xf2: InstructionDefinition('SET_D_6', 0, 2),
    0xf3: InstructionDefinition('SET_E_6', 0, 2),
    0xf4: InstructionDefinition('SET_H_6', 0, 2),
    0xf5: InstructionDefinition('SET_L_6', 0, 2),
    0xf6: InstructionDefinition('SET_HL_6', 0, 4),
    0xf7: InstructionDefinition('SET_A_6', 0, 2),
    
    0xf8: InstructionDefinition('SET_B_7', 0, 2),
    0xf9: InstructionDefinition('SET_C_7', 0, 2),
    0xfa: InstructionDefinition('SET_D_7', 0, 2),
    0xfb: InstructionDefinition('SET_E_7', 0, 2),
    0xfc: InstructionDefinition('SET_H_7', 0, 2),
    0xfd: InstructionDefinition('SET_L_7', 0, 2),
    0xfe: InstructionDefinition('SET_HL_7', 0, 4),
    0xff: InstructionDefinition('SET_A_7', 0, 2),

    0x20: InstructionDefinition('SLA_B', 0, 2),
    0x21: InstructionDefinition('SLA_C', 0, 2),
    0x22: InstructionDefinition('SLA_D', 0, 2),
    0x23: InstructionDefinition('SLA_E', 0, 2),
    0x24: InstructionDefinition('SLA_H', 0, 2),
    0x25: InstructionDefinition('SLA_L', 0, 2),
    0x26: InstructionDefinition('SLA_HL', 0, 4),
    0x27: InstructionDefinition('SLA_A', 0, 2),

    0x28: InstructionDefinition('SRA_B', 0, 2),
    0x29: InstructionDefinition('SRA_C', 0, 2),
    0x2a: InstructionDefinition('SRA_D', 0, 2),
    0x2b: InstructionDefinition('SRA_E', 0, 2),
    0x2c: InstructionDefinition('SRA_H', 0, 2),
    0x2d: InstructionDefinition('SRA_L', 0, 2),
    0x2e: InstructionDefinition('SRA_HL', 0, 4),
    0x2f: InstructionDefinition('SRA_A', 0, 2),

}

## SLA r8
## SLA [HL]
## SRA r8
## SRA [HL]
